version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/test-server.Dockerfile
    volumes:
      - ./imports:/blockcluster/imports
      - ./client:/blockcluster/client
      - ./server:/blockcluster/server
      - ./public:/blockcluster/public
      - ./private:/blockcluster/private
      - ./packages:/blockcluster/packages
      - ./.meteor:/blockcluster/.meteor
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
