version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    volumes:
      - ./imports:/blockcluster/imports:cached
      - ./client:/blockcluster/client:cached
      - ./server:/blockcluster/server:cached
      - ./public:/blockcluster/public:cached
      - ./private:/blockcluster/private:cached
      - ./packages:/blockcluster/packages:cached
      - ./.meteor:/blockcluster/.meteor:cached
      - ./.meteor/this-does-not-exists:/blockcluster/.meteor/local:cached
    ports:
      - '3000:3000'

    depends_on:
      - configserver
      - licenceservice
      - redis
    environment:
      NODE_ENV: development
      CONFIG_URL: http://configserver:3005
      LICENCE_SERVICE_HOST: http://licenceservice:4000
      MONGO_URL: mongodb://35.161.9.16:32153
      REDIS_HOST: redis
      REDIS_PORT: 6379
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '3'
        reservations:
          memory: 1G
          cpus: '1'

  configserver:
    image: 402432300121.dkr.ecr.ap-south-1.amazonaws.com/blockcluster-daemon:latest
    ports:
      - '3005:3005'
    volumes:
    - ./volumes/conf.d:/conf.d:cached
    deploy:
      resources:
        limits:
          memory: 200M
          cpus: '0.1'
        reservations:
          memory: 50M
          cpus: '0.1'

  licenceservice:
    build:
      context: ../licensing-microservice
      dockerfile: ../licensing-microservice/Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ../licensing-microservice/Templates:/src/Templates
      - ../licensing-microservice/config:/src/config
      - ../licensing-microservice/index.js:/src/config/index.js
      - ../licensing-microservice/apis:/src/apis
      - ../licensing-microservice/schema:/src/schema
    environment:
      MONGO_URL: mongodb://35.161.9.16:32153
      NODE_ENV: development

  redis:
    image: redis
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          memory: 400M
          cpus: '0.1'
        reservations:
          memory: 100M
          cpus: '0.1'


