---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "server.name" . }}-deploy
  namespace: {{ template "server.namespace" . }}
  labels:
    name: {{ template "server.name" . }}
    app: {{ template "server.app" . }}
    release: {{ .Release.Name }}
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: {{ template "server.name" . }}
  template:
    metadata:
      labels:
        name: {{ template "server.name" . }}
        app: {{ template "server.app" . }}
        env: {{ .Values.NODE_ENV }}
    spec:
{{- include "server.nodeAffinities" . | indent 6 }}
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /webapp-logs/
          type: ""
        name: webapp-logs
      containers:
      - name: {{ template "server.name" . }}
        volumeMounts:
          - mountPath: /tmp/logs/
            name: webapp-logs
        image: {{ .Values.image }}:{{ template "server.image-tag" . }}
        imagePullPolicy: IfNotPresent
        workingDir: /blockcluster
        env:
        - name: WEB_ENV
          value: {{ .Values.NODE_ENV | quote }}
        - name: NODE_ENV
          value: {{ .Values.NODE_ENV | quote }}
        - name: MONGO_URL
          value: {{ template "server.monogUrl" . }}
        - name: ROOT_URL
          value: {{ template "server.rootUrl" . }}
        - name: REDIS_HOST
          value: {{ template "envs.redisHost" . }}
        - name: REDIS_PORT
          value: {{ template "envs.redisPort" . }}
        - name: NAMESPACE
          value: {{ template "server.namespace" . }}
        - name: IS_BLOCKCLUSTER_CLOUD
          value: "1"
        - name: NETWORK_UPDATE_ID
          value: {{ .Values.NETWORK_UPDATE_ID }}
        - name: NETWORK_UPDATE_KEY
          value: {{ .Values.NETWORK_UPDATE_KEY }}
        - name: COMMIT_HASH
          value: {{ .Values.COMMIT_HASH }}
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: sendgrid-creds
              key: apiKey
        - name: RAZORPAY_ID
          valueFrom:
            secretKeyRef:
              name: razorpay-creds
              key: razorPayId
        - name: RAZORPAY_KEY
          valueFrom:
            secretKeyRef:
              name: razorpay-creds
              key: razorPaySecret
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_ENV
          value: {{ .Values.NODE_ENV }}
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/webapp.lock
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ping
            port: 3000
          timeoutSeconds: 1
          periodSeconds: 5
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "150m"
          limits:
            memory: "1Gi"
            cpu: "600m"
      imagePullSecrets:
      - name: regsecret


