---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "server.name" . }}-hpa
  namespace: {{ template "server.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ template "server.name" . }}-deploy
  targetCPUUtilizationPercentage: 60
  minReplicas: {{ template "server.minReplicas" . }}
  maxReplicas: {{ template "server.maxReplicas" . }}
