---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  name: {{ template "server.name" . }}-ing
  namespace: {{ template "server.namespace" . }}
spec:
{{- if eq .Values.NODE_ENV "production" }}
  tls:
  - hosts:
    - app.blockcluster.io
    - admin.blockcluster.io
    secretName: blockcluster-ssl
  rules:
  - host: app.blockcluster.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "server.name" . }}-svc
          servicePort: 80
  - host: admin.blockcluster.io
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "server.name" . }}-svc
          servicePort: 80
{{- else }}
  tls:
  - hosts:
    - {{ template "server.host" . }}
    secretName: blockcluster-ssl
  rules:
  - host: {{ template "server.host" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "server.name" . }}-svc
          servicePort: 80
{{- end -}}
